# Generated by Django 2.2.dev20180906114925 on 2018-10-13 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estadio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('estadio', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='estadisticas.Estadio')),
            ],
        ),
        migrations.CreateModel(
            name='Encuentro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.TimeField()),
                ('golesLocal', models.IntegerField(default=0)),
                ('golesVisitante', models.IntegerField(default=0)),
                ('equipo1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipo1', to='estadisticas.Equipo')),
                ('equipo2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipo2', to='estadisticas.Equipo')),
                ('estadio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estadisticas.Estadio')),
            ],
        ),
    ]
