# Generated by Django 2.2.dev20180906114925 on 2018-10-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadisticas', '0003_encuentro_jornada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuentro',
            name='jornada',
            field=models.IntegerField(default=0),
        ),
    ]
